### PR TITLE
tests: rebuild tests on open only if the project is configured

### LINKED ISSUE #155: Initial configuration failure:  mesonbuild.reconfigure command not found on first setup
When opening a meson project for the first time (so not configured at all);

Trying to run `Meson: reconfigure` result in an error message `command 'mesonbuild.reconfigure' command not found`.
Regression has been introduced in commit https://github.com/mesonbuild/vscode-meson/commit/5ddca809784bf076344584847a589aa2c5f30633 . `rebuildTests`, in the extension init, never finish.

### PR DESCRIPTION
**Pull request by ylatuya**
fixes #155

### CODE REVIEW

**Comment by tristan957** [comment]
Can you add a changelog note?

**Comment by ylatuya** [comment]
This should fix the issue. It requires a bit more testing but I am unable to build from main so I haven't been able to test it

**Comment by tristan957** [comment]
Why can't you build from main?

**Comment by ylatuya** [comment]
That's the error:

```
src/utils.ts:31:33 - error TS2322: Type 'ExecFileException | undefined' is not assignable to type 'ExecException | undefined'.
  Type 'ExecFileException' is not assignable to type 'ExecException | undefined'.
    Type 'ExecFileException' is not assignable to type 'ExecException'.
      Types of property 'code' are incompatible.
        Type 'string | number | null | undefined' is not assignable to type 'number | undefined'.
          Type 'null' is not assignable to type 'number | undefined'.

31       resolve({ stdout, stderr, error: error ? error : undefined });
                                   ~~~~~


Found 1 error in src/utils.ts:31
```

**Comment by tristan957** [comment]
Is it possible your dependencies are out of date?

**Comment by ylatuya** [comment]
Yes, that was it. I cleaned up everything, re-installed deps and now it launches. Testing now the fix.

**Comment by tristan957** [comment]
Cool. Also just throw in a `Fixes [#155](https://github.com/mesonbuild/vscode-meson/issues/155)` in the changelog after confirming.
